apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: mysql-verticalscaling-
  generateName: mysql-verticalscaling-
  namespace: default
spec:
  clusterRef: wesql
  type: VerticalScaling
  ttlSecondsAfterSucceed: 600
  verticalScaling:
  - componentName: wesql
    requests:
        memory: "390Mi"
        cpu: "280m"
    limits:
        memory: "470Mi"
        cpu: "300m"
