apiVersion: apps.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: mysql-horizontalscaling-
  generateName: mysql-horizontalscaling-
  namespace: default
spec:
  clusterRef: wesql
  type: HorizontalScaling
  horizontalScaling:
  - componentName: wesql
    replicas: 3
