apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: kubeblocks
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/version: 0.8.1
    helm.sh/chart: kubeblocks-0.8.1
  name: kubeblocks-host-ports
