# Source: kubeblocks/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeblocks-manager-config
  labels:
    helm.sh/chart: kubeblocks-0.8.1
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.8.1"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    # data plane tolerations
    DATA_PLANE_TOLERATIONS: '[{"effect":"NoSchedule","key":"kb-data","operator":"Equal","value":"true"}]'

    # data plane affinity
    DATA_PLANE_AFFINITY: '{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"kb-data","operator":"In","values":["true"]}]},"weight":100}]}}'

    # the default storage class name.
    DEFAULT_STORAGE_CLASS: ""
---
# Source: kubeblocks/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeblocks-host-ports
  labels:
    helm.sh/chart: kubeblocks-0.8.1
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.8.1"
    app.kubernetes.io/managed-by: Helm
data: {}
---
# Source: kubeblocks/templates/applications/alertmanager-webhook-adaptor-values.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-webhook-adaptor-chart-kubeblocks-values
  labels:
    helm.sh/chart: kubeblocks-0.8.1
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.8.1"
    app.kubernetes.io/managed-by: Helm
data:
  values-kubeblocks-override.yaml: |-
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: kb-controller
              operator: In
              values:
              - "true"
          weight: 100
    configFiles:
      config.yaml: {}
    configMapOverrideName: config
    image:
      registry: infracreate-registry.cn-zhangjiakou.cr.aliyuncs.com
---
# Source: kubeblocks/templates/applications/apecloud-otel-collector-values.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: apecloud-otel-collector-chart-kubeblocks-values
  labels:
    helm.sh/chart: kubeblocks-0.8.1
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.8.1"
    app.kubernetes.io/managed-by: Helm
data:
  values-kubeblocks-override.yaml: |-
    enabled: false
    image:
      registry: infracreate-registry.cn-zhangjiakou.cr.aliyuncs.com
